### ISSUE TITLE
Magic Link via iOS/Android

### ISSUE THREAD

**Issue by shinriyo** [supasquad/supabase-flutter-quickstart#3]
Does it support only "Magic Link" in web?

```
Magic Link
Follow this link to login:

Log In
```

**Comment by dshukertjr** [comment]
"Magic Link" is supported on iOS and Android as well. You can follow the instructions [here](https://supabase.io/docs/guides/with-flutter) to find out how to do so, but in short, `supabase_flutter` package uses deeplink to bring the user back to the app upon clicking the `Log In` link on the email.

**Comment by shinriyo** [comment]
@dshukertjr Thank you for replying
I did this by using an iOS simulator and logged in in email.
But, should I always log without email?

**Comment by dshukertjr** [comment]
@shinriyo 
Sorry, couldn't quite understand your question, but do you mean "should you always use Magic Link?" by saying "should I always log without email?"?

**Comment by shinriyo** [comment]
thank you for response.
I'm sorry. I am not good at English.

I wanted to say
"should I always log in with the link that sent via email?"

because, once logged in, I want to log in without email's link next time.

**Comment by dshukertjr** [comment]
@shinriyo 
That's fine!

You can sign in using variety of options that Supabase provides. If you just want a simple way of signing users in, maybe [sining users in with email and password](https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-email) is the one for you!
